### ISSUE TITLE
chief brokkr & bike

### ISSUE THREAD

**Issue by cultistapazzo** [BSData/deadzone#13]
chief brokkr lacks dismantle
brokkr bike lacks evade
thanks for your work ^^

**Comment by cultistapazzo** [comment]
i have bs 2.01.14 and data 3.0.4 and I still don't see them :(

**Comment by BAE2** [comment]
Ahh, now that is strange.  Do you know anyone else that can replicate the issue?  It appears on mine so it's hard to diagnose!

**Comment by cultistapazzo** [comment]
yep, a friend of mine has the same problem, but I've ask on the fb group, maybe helps. if you need some screen just ask

many thanks again :)

**Comment by cultistapazzo** [comment]
just here to say, BS version 2.01.15, data 3.0.5 and the problem is the same

some screen:
https://i.imgur.com/pH1Bi8I.jpg
https://i.imgur.com/lqMYGrK.jpg
https://i.imgur.com/nTF4EvC.jpg

**Comment by BAE2** [comment]
I've done a load of updates on the files.  Delete previous data and use new files, and then see whether the problem persists.

**Comment by cultistapazzo** [comment]
thanks for your work

but chief brokkr still lacks dismantle
brokkr bike still lacks evade

bjarn now it's ok

**Comment by BAE2** [comment]
Just noticed you said you're using release 3.0.5 - they may have been fixed in releases 3.0.6, 3.0.7 or 3.0.8.  3.1 was released yesterday so update data and see what happens.  As always, make sure you select 'Delete existing data first'.

**Comment by cultistapazzo** [comment]
updated to 3.1 and still the same :(

**Comment by BAE2** [comment]
Then I'm stumped!!  I have asked members of Deadzone Fanatics on FB to see whether anyone else can replicate the issue.

**Comment by BAE2** [comment]
We may have something!  Someone on DZ Fanatics found the same issue, and was able to fix it:

"So I deleted all the data manually then readded 3.1 and it seems to have fixed. The first time around I did click delete previous data but it didn’t work obviously"

Could you try this?

**Comment by BAE2** [comment]
Did this work for you?

**Comment by cultistapazzo** [comment]
i have tryed some days ago and nothing happen.
i try now and it's works! dunno why but thanks :D
