### ISSUE TITLE
[Anon] Bug report: Asterians.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/deadzone#18]
**File:** Asterians.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** The pts cost for Black Talon Prime leader is listed at 29 pts, shoudl be 28 according to Outbrreak.

**Comment by BAE2** [comment]
Error caused by 1pt Pistol change in Outbreak.  Updated.
