### ISSUE TITLE
[Anon] Bug report: Marauders.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/deadzone#19]
**File:** Marauders.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Chief Radgrad splat ability 'Make it to payday' missing description. Radgrad elite list also not appearing.

**Comment by BAE2** [comment]
Added splat description.  I cannot replicate his list options not appearing once he has been selected though?
