### ISSUE TITLE
can't download the data

### ISSUE THREAD

**Issue by cultistapazzo** [BSData/deadzone#34]
Details:

BattleScribe failed to download and import one or more data files from the repository.

1) https://battlescribedata.appspot.com/repos/deadzone/Mazon_Labs.catz: Game system not found for catalogue Mazon_Labs.catz

2) https://battlescribedata.appspot.com/repos/deadzone/Forge_Fathers.catz: Game system not found for catalogue Forge_Fathers.catz

3) net.battlescribe.model.dataindex.DataIndexEntry@69c78cc2: Read timed out

4) https://battlescribedata.appspot.com/repos/deadzone/Nameless.catz: Game system not found for catalogue Nameless.catz

5) net.battlescribe.model.dataindex.DataIndexEntry@1d5d586a: Read timed out

6) https://battlescribedata.appspot.com/repos/deadzone/The_GCPS.catz: Game system not found for catalogue The_GCPS.catz

7) https://battlescribedata.appspot.com/repos/deadzone/The_Plague.catz: Game system not found for catalogue The_Plague.catz

8) https://battlescribedata.appspot.com/repos/deadzone/Marauders.catz: Game system not found for catalogue Marauders.catz

9) https://battlescribedata.appspot.com/repos/deadzone/Mercs.catz: Game system not found for catalogue Mercs.catz

10) net.battlescribe.model.dataindex.DataIndexEntry@2c07406c: Read timed out

11) https://battlescribedata.appspot.com/repos/deadzone/Enforcers.catz: Game system not found for catalogue Enforcers.catz
	at net.battlescribe.a.a.c(BattleScribe:1746)
	at net.battlescribe.a.a.a(BattleScribe:1433)
	at net.battlescribe.a.a.a(BattleScribe:1415)
	at net.battlescribe.desktop.common.BattleScribeFrame$7.a(BattleScribe:471)
	at net.battlescribe.desktop.common.BattleScribeFrame$7.doInBackground(BattleScribe:466)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by amis92** [comment]
@BAE2 

Honestly, I can only say that I have no idea why the GST is not indexed into the web server.

I'll restart the server tomorrow morning to force it a re-indexing operation. It's all I can do, honestly.

**Comment by amis92** [comment]
@BAE2 I've found the culprit. The `Nameless` catalogue has the same ID as the game system, which results in the catalogue "overwriting" the game system during indexing.

https://github.com/BSData/deadzone/search?q=9491-c0e3-ba03-047b&unscoped_q=9491-c0e3-ba03-047b

You need to change the Nameless's ID.

**Comment by amis92** [comment]
Code responsible in question: https://github.com/BSData/bsdata/blob/f32606ff6833742667d6b3586119da032e5a01b6/src/main/java/org/battlescribedata/repository/Indexer.java#L130-L132

**Comment by BAE2** [comment]
I think this should be sorted now!

**Comment by amis92** [comment]
@BAE2 will need to create a new release and then it'll need to be processed by webserver.
