### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by totogt06** [BSData/deadzone#43]
Hacker Halftail was fixed for specialists but his points and VP are still switched in the Leader section. Also the It Burns! description has missing letters for a few "fire" and "flames" wording in all factions.
Misspelling words in quotes below
-Enforcer "Peacekeeper" Captain
-TAG and Sniper Scope rule: last sentence "benefit"
-Tactician 1,2,3: last sentence "benefit"
-Vehicle rule: "battlefield" missing letters throughout description 
-Veermyn Piper swarm lord rule: "model"

**Comment by HeWhoWatches** [comment]
@totogt06 Thanks for reporting, and apologies it's taken me some time to get around to putting the fixes in place.

**Comment by totogt06** [comment]
No worries. Just wanted new folks to not be discouraged. Looking forward to the new units and changes!

Sent from my U.S.Cellular© Smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
