### ISSUE TITLE
[Anon] Bug report: Deadzone 3rd Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/deadzone#56]
**File:** Deadzone 3rd Edition.gstz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** Forge Fathers Artificer specialist comes with both weapon options already selected and double cost, cannot select only one of them.

**Comment by JamesMoyon** [comment]
This will be fixed in Forge Fathers v5.

**Comment by KurganFr** [comment]
Issue has now been resolved.
