### ISSUE TITLE
[Anon] Bug report: Marauders 3rd Edition.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/deadzone#59]
**File:** Marauders 3rd Edition.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Marauder ripper warlord is missing the special order none shall pass

**Comment by KurganFr** [comment]
Working on a release that will fix this issue.

**Comment by KurganFr** [comment]
Resolved in v5.11.0.
