### ISSUE TITLE
Current issues with datafiles.

### ISSUE THREAD

**Issue by scarletsquig** [BSData/deadzone#6]
Iron Ancestor missing from Forge Fathers.
Enforcer Peacekeepers all classified as leaders.
Enforcer Strider, Pathfinder and Pathfinder Bike all classified under "no category".
Stuntbot missing from Marauders. Also the new Orx units with no cards released.
Plague Strider missing. Also plague enforcer.

**Comment by BAE2** [comment]
All files are replaced
