### ISSUE TITLE
[Anon] Bug report: Deadzone_2nd_Ed.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/deadzone#8]
**File:** Deadzone_2nd_Ed.gstz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** Hi,
all the mercs don't have their special abilities in their description( only the character "nem-rath" has them), but these special abilities are listed below all togheter with their explanation.

**Comment by BAE2** [comment]
That was actually a mistake on Nem-Rath - the only way to enable items (which are specific to the list) to be taken on Mercs is to have them as their own subcategory, with items alongside.  The unfortunately side-effect of this is that when in 'Minimal' view, it hides much of the information.  However, when investigating Nem-Rath I discovered a weird quirk - if the selections (weapons and items) are given a point value they and their ability appear on the minimal view.  As such I have given a '1pts' value to all selections within Mercs and reduced the model points to account for this addition.  This keeps the same overall cost while improving the information shown on Minimal view.
